on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install modules
        run: yarn
      - name: Build project
        run: yarn build
      - name: Test each data feed
        run: yarn test test/oracle/check-each-data-feed.test.ts
      - name: Big test for avalanche-prod data feed
        run: yarn test test/oracle/big-test-avalanche-prod.test.ts
